obj-$(CONFIG_TOUCHSCREEN_ILITEK_CHIPSET) += ilitek_v3_mmi.o

ccflags-$(CONFIG_TOUCHSCREEN_ILITEK_ESD) += -DILI_CONFIG_ESD
ccflags-$(CONFIG_INPUT_ILI_ENABLE_DOUBLE_TAP) += -DILI_SENSOR_EN
ccflags-$(CONFIG_INPUT_ILI_BOARD_USES_DOUBLE_TAP_CTRL) += -DILI_DOUBLE_TAP_CTRL
ccflags-$(CONFIG_INPUT_ILI_BOARD_USES_DOUBLE_TAP_CTRL) += -DILI_PRIMARY_NODE
ccflags-$(CONFIG_INPUT_ILI_SET_TOUCH_STATE) += -DILI_SET_TOUCH_STATE
ccflags-$(CONFIG_INPUT_ILI_PANEL_NOTIFICATIONS) += -DILI_CONFIG_PANEL_NOTIFICATIONS
ccflags-$(CONFIG_ILITEK_RESUME_BY_DDI) += -DILI_CONFIG_RESUME_BY_DDI
ccflags-$(CONFIG_ILITEK_CHARGER) += -DILI_CONFIG_MTK_CHARGER
ccflags-$(CONFIG_ILITEK_MTK_CHECK_PANEL) += -DILI_MTK_CHECK_PANEL
ccflags-$(CONFIG_ILITEK_MULTI_TP_MODULE) += -DILI_TP_MODULE_EN
ccflags-$(CONFIG_ILI_TOUCH_LAST_TIME) += -DILI_TOUCH_LAST_TIME
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI
ccflags-$(CONFIG_INPUT_ILI_STOWED_MODE_EN) += -DILI_STOWED_MODE_EN

ilitek_v3_mmi-objs += ilitek_v3.o
ilitek_v3_mmi-objs += ilitek_v3_spi.o
ilitek_v3_mmi-objs += ilitek_v3_qcom.o
ilitek_v3_mmi-objs += ilitek_v3_ic.o
ilitek_v3_mmi-objs += ilitek_v3_touch.o
ilitek_v3_mmi-objs += ilitek_v3_mp.o
ilitek_v3_mmi-objs += ilitek_v3_hostdl.o
ilitek_v3_mmi-objs += ilitek_v3_node.o
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
