# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -Wall
ccflags-y += -I$(srctree)/include/linux/input/awinic
ccflags-y += -I$(src)/../..

ifneq ($(filter m y,$(CONFIG_AW96XX_POWER_SUPPLY_ONLINE)),)
    ccflags-y += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

obj-m += awinic_sar.o

awinic_sar-objs := \
    comm/aw_sar_comm_interface.o \
    aw_sar.o \
    aw9610x/aw9610x.o \
    aw9620x/aw9620x.o \
    aw9620x/aw_update_fw.o \
    aw963xx/aw963xx.o
