HAVE_KERNEL_5_4 = $(shell test -d $(ANDROID_BUILD_TOP)/kernel/msm-5.4 && echo 1)
HAVE_KERNEL_5_15 = $(shell test -d $(ANDROID_BUILD_TOP)/kernel_platform/gki/kernel/5.15 && echo 1)

ifeq ($(HAVE_KERNEL_5_4),1)
ZRAM_SRC = zram-5.4
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_4
else ifeq ($(HAVE_KERNEL_5_15),1)
ZRAM_SRC = zram-5.15
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_15
else
ZRAM_SRC = zram-5.10
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_10
endif

ccflags-$(CONFIG_HYBRIDSWAP_ZRAM) += -DCONFIG_HYBRIDSWAP_ZRAM
ccflags-$(CONFIG_HYBRIDSWAP_ZRAM_WRITEBACK) += -DCONFIG_HYBRIDSWAP_ZRAM_WRITEBACK
ccflags-$(CONFIG_HYBRIDSWAP) += -DCONFIG_HYBRIDSWAP
ccflags-$(CONFIG_HYBRIDSWAP_SWAPD) += -DCONFIG_HYBRIDSWAP_SWAPD
ccflags-$(CONFIG_HYBRIDSWAP_CORE) += -DCONFIG_HYBRIDSWAP_CORE

moto_swap-objs += $(ZRAM_SRC)/zram_drv.o
moto_swap-objs += hybridswap/hybridswap_main.o
moto_swap-objs += hybridswap/hybridswap_eswap.o

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ASYNC_COMPRESS)),)
moto_swap-objs += hybridswap/hybridswap_akcompress.o
endif

moto_swap-objs += hybridswap/hybridswap_swapd.o
moto_swap-objs += $(ZRAM_SRC)/zcomp.o

obj-$(CONFIG_MOTO_SWAP) += moto_swap.o
