# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

moto_f_usbnet-objs += f_usbnet.o
obj-$(CONFIG_MOTO_F_USBNET) += moto_f_usbnet.o
