# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
# removed vendor include

ifneq ($(filter m y,$(CONFIG_VIBRATOR_NOISE_CAMERA)),)
	EXTRA_CFLAGS += -DCONFIG_VIBRATOR_NOISE_CAMERA
endif

ldo_vibrator_mmi-y += moto_ldo_vibrator.o

obj-y += ldo_vibrator_mmi.o

