# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

ifneq ($(filter y,$(CONFIG_SEC_NFC_PRODUCT_N5)),)
	EXTRA_CFLAGS += -DCONFIG_SEC_NFC_PRODUCT_N5
endif
ifneq ($(filter y,$(CONFIG_SEC_NFC_IF_I2C)),)
	EXTRA_CFLAGS += -DCONFIG_SEC_NFC_IF_I2C
endif

obj-y        += sec_nfc.o
